<?php

/**
 * This snippet is a solution to the Problem 2 of ProjectEuler.com
 * I am using this to help my problem solving skill.
 * Question:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 *            1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */

$second = 2;
$first = 1;
$sum = 2;
$_num = 0;
while ($_num < 4000000) {
    $_num = $second + $first;

    $first = $second;
    $second = $_num;

    if (!($_num % 2)) {
        $sum+= $_num;
    }
}
echo $sum;

